- name: install Node.js package(s) for Redhat/CentOS
  yum: pkg={{ item }} state=latest
  with_items:
    - nodejs
    - npm
  when: ansible_os_family == "RedHat"

- name: install Node.js package(s) for Debian/Ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - nodejs
    - npm
  when: ansible_os_family == "Debian"
